(()=>{
const core=document.createElement('script');
core.src='https://cdn.jsdelivr.net/gh/Vincentfeliciano11/Cancer-Immunotherapy-Pembrolizumab-@e425b9a0d506eb7d8d3e735f1462bad002f60c9c/effects.js';
core.onload=()=>{
const globalStyle=document.createElement('style');globalStyle.textContent=`
.info-card,.info-card.lab-glass{background:#fff!important;background-image:none!important;color:#0752ad!important;opacity:1;border:clamp(5px,1vw,8px) solid #092e5d!important;box-shadow:clamp(8px,1.5vw,18px) clamp(8px,1.5vw,18px) 0 #008cff,0 28px 65px #003a7a55!important;width:min(92vw,640px)!important;max-height:min(84vh,84dvh)!important;padding:clamp(22px,4vw,40px)!important;border-radius:clamp(8px,1.2vw,14px)!important;overflow-y:auto!important;overscroll-behavior:contain!important;position:fixed!important;left:50%!important;top:50%!important;right:auto!important;bottom:auto!important;transform:translate(-50%,-50%) scale(.9)!important;z-index:20000!important}
.info-card.open,.info-card.lab-glass.open{transform:translate(-50%,-50%) scale(1)!important;pointer-events:auto!important;opacity:1!important}
.info-card:before{content:""!important;position:absolute!important;inset:0!important;background-image:radial-gradient(#008cff22 1.4px,transparent 1.4px)!important;background-size:11px 11px!important;pointer-events:none!important;opacity:.55!important}
.info-card:after{content:"";position:absolute;left:0;right:0;top:0;height:14px;background:linear-gradient(90deg,#ff8500 0 35%,#008cff 35% 70%,#ff8500 70%);border-bottom:3px solid #092e5d;pointer-events:none}
.info-card h3,.info-card p,.info-card .info-tag{position:relative!important;z-index:1!important;opacity:1!important}
.info-card h3{color:#0752ad!important;-webkit-text-fill-color:#0752ad!important;text-shadow:none!important;font-size:clamp(24px,5vw,40px)!important;line-height:1.02!important;margin:clamp(8px,2vw,14px) 54px 14px 0!important;overflow-wrap:anywhere!important}
.info-card p{color:#164f8a!important;-webkit-text-fill-color:#164f8a!important;text-shadow:none!important;font-size:clamp(15px,2.2vw,19px)!important;line-height:1.55!important;margin:0!important;overflow-wrap:anywhere!important}
.info-card .info-tag{background:#e9f5ff!important;color:#0752ad!important;-webkit-text-fill-color:#0752ad!important;border:2px solid #008cff!important;padding:6px 11px!important;font-size:clamp(11px,1.8vw,14px)!important;font-weight:1000!important;text-transform:uppercase!important;box-shadow:4px 4px 0 #092e5d22!important}
.close-info{position:absolute!important;right:10px!important;top:18px!important;width:clamp(42px,7vw,52px)!important;height:clamp(42px,7vw,52px)!important;border:4px solid #092e5d!important;background:#fff!important;color:#0752ad!important;font-size:clamp(24px,4vw,32px)!important;font-weight:1000!important;line-height:1!important;display:grid!important;place-items:center!important;cursor:pointer!important;z-index:5!important;box-shadow:4px 4px 0 #ff8500!important;border-radius:6px!important;touch-action:manipulation!important}
.close-info:hover,.close-info:focus-visible{background:#0752ad!important;color:#fff!important;outline:none!important;transform:translate(-1px,-1px)!important;box-shadow:6px 6px 0 #ff8500!important}
@media(max-width:900px){.info-card,.info-card.lab-glass{width:min(94vw,620px)!important;max-height:82dvh!important;padding:clamp(20px,5vw,34px)!important}.info-card h3{font-size:clamp(23px,7vw,36px)!important;margin-right:50px!important}.info-card p{font-size:clamp(15px,4vw,18px)!important}.close-info{right:8px!important;top:16px!important}}
@media(max-width:520px){.info-card,.info-card.lab-glass{width:94vw!important;max-height:80dvh!important;border-width:5px!important;box-shadow:8px 8px 0 #008cff,0 18px 40px #003a7a44!important}.info-card h3{font-size:clamp(22px,8vw,32px)!important}.info-card p{font-size:clamp(15px,4.5vw,17px)!important;line-height:1.48!important}}
`;document.head.appendChild(globalStyle);
const scopeStyle=document.createElement('style');scopeStyle.textContent=`.microscope-copy{overflow:hidden!important;overflow-y:hidden!important;scrollbar-width:none!important;-ms-overflow-style:none!important}.microscope-copy::-webkit-scrollbar{display:none!important}.microscope-copy:after{display:none!important;content:none!important}`;document.head.appendChild(scopeStyle);
const card=document.getElementById('infoCard');if(card){let close=card.querySelector('.close-info');if(!close){close=document.createElement('button');close.type='button';close.className='close-info';close.setAttribute('aria-label','Close description');close.textContent='×';card.prepend(close)}const shut=()=>card.classList.remove('open');close.addEventListener('click',shut);close.addEventListener('touchend',e=>{e.preventDefault();shut()},{passive:false});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&card.classList.contains('open'))shut()});card.addEventListener('click',e=>{if(e.target===card)shut()})}
const mobile=matchMedia('(max-width:900px), (hover:none), (pointer:coarse)').matches||navigator.maxTouchPoints>0;if(!mobile)return;
const css=document.createElement('style');css.textContent=`@media(max-width:900px),(hover:none),(pointer:coarse){.comic-panel{color:#fff!important;opacity:1!important;-webkit-text-fill-color:#fff!important;font-weight:1000!important;text-shadow:3px 3px 0 #032048,0 0 2px #032048!important;filter:saturate(1.08) contrast(1.08)!important;-webkit-font-smoothing:antialiased;text-rendering:geometricPrecision}.comic-panel span{color:inherit!important;opacity:1!important;-webkit-text-fill-color:currentColor!important;font-weight:1000!important;text-shadow:inherit!important}.panel-main span{color:#0752ad!important;-webkit-text-fill-color:#0752ad!important;background:#fff!important;opacity:1!important;text-shadow:none!important;border-color:#092e5d!important}.comic-panel:before{opacity:.55!important}.uv-mode .comic-panel{color:#fff!important;opacity:1!important;-webkit-text-fill-color:#fff!important;filter:saturate(1.18) contrast(1.12) brightness(1.08) drop-shadow(0 0 10px #8d2cff) drop-shadow(0 0 18px #13e6ff)!important}.uv-mode .panel-main span{color:#0752ad!important;-webkit-text-fill-color:#0752ad!important;background:#fff!important}}`;document.head.appendChild(css);
let ctx=null;const getCtx=()=>{try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;if(!ctx||ctx.state==='closed')ctx=new AC();return ctx}catch(e){return null}};const unlock=()=>{const c=getCtx();if(!c)return;if(c.state==='suspended')c.resume().catch(()=>{});try{const b=c.createBuffer(1,1,22050),s=c.createBufferSource();s.buffer=b;s.connect(c.destination);s.start(0)}catch(e){}};
const comic=()=>{const c=getCtx();if(!c)return;const run=()=>{try{const g=c.createGain(),a=c.createOscillator(),b=c.createOscillator();g.gain.setValueAtTime(.17,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.19);a.type='sawtooth';a.frequency.setValueAtTime(190,c.currentTime);a.frequency.exponentialRampToValueAtTime(520,c.currentTime+.09);b.type='square';b.frequency.setValueAtTime(95,c.currentTime);b.frequency.exponentialRampToValueAtTime(170,c.currentTime+.13);a.connect(g);b.connect(g);g.connect(c.destination);a.start();b.start();a.stop(c.currentTime+.19);b.stop(c.currentTime+.19)}catch(e){}};if(c.state==='suspended')c.resume().then(run).catch(()=>{});else run()};
const click=()=>{const c=getCtx();if(!c)return;const run=()=>{try{const g=c.createGain(),o=c.createOscillator();o.type='square';o.frequency.setValueAtTime(240,c.currentTime);o.frequency.exponentialRampToValueAtTime(115,c.currentTime+.055);g.gain.setValueAtTime(.14,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.075);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.08)}catch(e){}};if(c.state==='suspended')c.resume().then(run).catch(()=>{});else run()};
document.addEventListener('touchstart',unlock,{capture:true,passive:true});document.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse')unlock()},{capture:true,passive:true});let lastComic=0,lastUV=0;document.querySelectorAll('.comic-panel').forEach(p=>{p.addEventListener('touchend',()=>{lastComic=performance.now();comic()},{passive:true});p.addEventListener('click',()=>{if(performance.now()-lastComic>500)comic()})});const uv=document.querySelector('.uv-toggle');if(uv){uv.addEventListener('touchend',()=>{lastUV=performance.now();click()},{passive:true});uv.addEventListener('click',()=>{if(performance.now()-lastUV>500)click()})}
};core.onerror=()=>console.error('Unable to load core site effects.');document.head.appendChild(core);
})();